# Generated by Django 5.0.1 on 2024-01-07 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Linux', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='joined_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='phone',
            field=models.IntegerField(null=True),
        ),
    ]
